services:
    Borsaco\DoctrinePrefixBundle\Doctrine\ORM\Mapping\PrefixNamingStrategy:
        arguments: ['%doctrine_prefix_bundle.config%']
        calls:
            - [setContainer, ['@service_container']]
            - [setStrategy]
